import turtle
width=int(input("가로: "))
length=int(input("세로: "))
coordinate=list(map(int,input("x,y:").split()))
t = turtle.Turtle()
t.goto(coordinate[0],coordinate[1])
t.clear()
t.forward(width)
t.left(90)
t.forward(length)
t.left(90)
t.forward(width)
t.left(90)
t.forward(length)
